{% set name = "cdst" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: python
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cdst-{{ version }}.tar.gz
  sha256: 21024b90547a01f33245e66df75c059722eee839f79b91464ad85c74faa15b93

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython >=0.29.25
    - pip
    - python >=3.8
  run:
    - cython >=0.29.24
    - gekko >="1.0.2"
    - numpy >="1.20.0"
    - pandas
    - python
    - ray >=1.12.0
    - scikit-learn
    - skorch
    - tensorboardx
    - tensorflow
    - torch >=1.9.0

test:
  imports:
    - cdst
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Bayer-Group/cdst
  summary: Calvin's Data Science Toolbox
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://github.com/Bayer-Group/cdst/wiki"
  dev_url: https://github.com/Bayer-Group/cdst

extra:
  recipe-maintainers:
    - calvinwy
