{% set name = "cdst" %}
{% set version = "0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 21024b90547a01f33245e66df75c059722eee839f79b91464ad85c74faa15b93

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python>=3.8
  run:
    - python>=3.8

about:
  home: The package home page
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: "Calvin's Data Science Toolbox"
  doc_url: https://github.com/Bayer-Group/cdst/wiki"
  dev_url: https://github.com/Bayer-Group/cdst

extra:
  recipe-maintainers:
    - calvinwy
